-- Migration: 0065_category_taxonomy_v2
-- Date: 2026-06-01
-- Replaces all listing_categories with new taxonomy (89 categories)

-- Clear existing categories
DELETE FROM listing_categories;

-- Insert new top-level categories
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
-- TOP-LEVEL (10)
('vehicles', 'Vehicles', 'vehicles', 'Cars, motorcycles, boats, and other vehicles', '🚗', NULL, 1, 1, '[{"name":"make","type":"text","label":"Make/Brand","required":true},{"name":"model","type":"text","label":"Model","required":true},{"name":"year","type":"number","label":"Year","required":true,"min":1900,"max":2027},{"name":"condition","type":"select","label":"Condition","required":true,"options":["New","Like New","Excellent","Good","Fair","For Parts"]},{"name":"price","type":"number","label":"Price","required":true,"min":0},{"name":"negotiable","type":"boolean","label":"Price Negotiable"},{"name":"mileage","type":"number","label":"Mileage (km)","min":0},{"name":"fuelType","type":"select","label":"Fuel Type","options":["Petrol","Diesel","Electric","Hybrid","LPG","CNG","Other"]},{"name":"transmission","type":"select","label":"Transmission","options":["Manual","Automatic","Semi-Auto","CVT"]},{"name":"color","type":"text","label":"Color"},{"name":"description","type":"textarea","label":"Description"},{"name":"features","type":"multi-select","label":"Features","options":["Sunroof","Leather Seats","GPS Navigation","Bluetooth","Backup Camera","Heated Seats","Cruise Control","4WD/AWD","ABS","Airbags","Parking Sensors","Apple CarPlay","Android Auto","Adaptive Cruise","Lane Keep Assist"]},{"name":"images","type":"images","label":"Photos","max":16},{"name":"registered","type":"boolean","label":"Vehicle Registered"},{"name":"registeredUntil","type":"date","label":"Registration Valid Until"},{"name":"warranty","type":"boolean","label":"Warranty Available"},{"name":"deliveryAvailable","type":"boolean","label":"Delivery Available"},{"name":"exchangeAccepted","type":"boolean","label":"Exchange/Trade Accepted"}]'),
('property-sale', 'Property Sale', 'property-sale', 'Real estate for sale', '🏠', NULL, 2, 1, '[{"name":"propertyType","type":"select","label":"Property Type","required":true,"options":["House","Apartment","Condo","Townhouse","Duplex","Land","Commercial","Industrial"]},{"name":"price","type":"number","label":"Price","required":true,"min":0},{"name":"negotiable","type":"boolean","label":"Price Negotiable"},{"name":"condition","type":"select","label":"Condition","options":["New","Excellent","Good","Needs Renovation","Under Construction"]},{"name":"landSize","type":"number","label":"Land Size (m²)","min":0},{"name":"buildingSize","type":"number","label":"Building Size (m²)","min":0},{"name":"bedrooms","type":"number","label":"Bedrooms","min":0},{"name":"bathrooms","type":"number","label":"Bathrooms","min":0,"max":20},{"name":"floors","type":"number","label":"Number of Floors","min":1},{"name":"parkingSpaces","type":"number","label":"Parking Spaces","min":0},{"name":"location","type":"text","label":"Address","required":true},{"name":"city","type":"text","label":"City/Town"},{"name":"district","type":"text","label":"District/Area"},{"name":"features","type":"multi-select","label":"Features & Amenities","options":["Garden","Swimming Pool","Garage","Balcony","Security System","Elevator/Lift","Furnished","Air Conditioning","Central Heating","Water Supply 24/7","Electricity 24/7","Internet/WiFi","Cable TV","Fire Alarm","Wheelchair Accessible"]},{"name":"viewType","type":"multi-select","label":"View Type","options":["City View","Sea View","Mountain View","Garden View","Pool View","River View","No Specific View"]},{"name":"ownershipType","type":"select","label":"Ownership Type","options":["Freehold","Leasehold","Strata/Condo","Cooperative","Government Lease"]},{"name":"titleDeedAvailable","type":"boolean","label":"Title Deed Available"},{"name":"yearBuilt","type":"number","label":"Year Built"},{"name":"description","type":"textarea","label":"Description"},{"name":"images","type":"images","label":"Photos","max":20},{"name":"videoTour","type":"url","label":"Video Tour URL"}]'),
('for-sale', 'For Sale', 'for-sale', 'Items for sale by individuals and businesses', '🛒', NULL, 3, 1, '[{"name":"title","type":"text","label":"Title","required":true,"maxLength":100},{"name":"category","type":"category","label":"Category","required":true},{"name":"condition","type":"select","label":"Condition","required":true,"options":["New","Like New","Excellent","Good","Fair","For Parts"]},{"name":"price","type":"number","label":"Price","required":true,"min":0},{"name":"negotiable","type":"boolean","label":"Price Negotiable"},{"name":"quantity","type":"number","label":"Quantity Available","min":1,"defaultValue":1},{"name":"brand","type":"text","label":"Brand"},{"name":"model","type":"text","label":"Model/Serial Number"},{"name":"color","type":"text","label":"Color"},{"name":"size","type":"text","label":"Size"},{"name":"material","type":"text","label":"Material"},{"name":"dimensions","type":"text","label":"Dimensions (L x W x H)"},{"name":"weight","type":"number","label":"Weight (kg)","min":0},{"name":"warranty","type":"boolean","label":"Warranty Available"},{"name":"warrantyExpiry","type":"date","label":"Warranty Expires"},{"name":"originalPackaging","type":"boolean","label":"Original Packaging"},{"name":"receiptAvailable","type":"boolean","label":"Receipt Available"},{"name":"location","type":"text","label":"Location"},{"name":"deliveryAvailable","type":"boolean","label":"Delivery Available"},{"name":"deliveryFee","type":"number","label":"Delivery Fee"},{"name":"meetupPreferred","type":"boolean","label":"Meetup Preferred"},{"name":"description","type":"textarea","label":"Description"},{"name":"defects","type":"textarea","label":"Known Defects/Issues"},{"name":"images","type":"images","label":"Photos","max":12}]'),
('jobs', 'Jobs', 'jobs', 'Employment opportunities and job postings', '💼', NULL, 4, 1, '[{"name":"jobTitle","type":"text","label":"Job Title","required":true,"maxLength":100},{"name":"companyName","type":"text","label":"Company Name","required":true},{"name":"companyLogo","type":"image","label":"Company Logo"},{"name":"companySize","type":"select","label":"Company Size","options":["1-10","11-50","51-200","201-500","501-1000","1000+"]},{"name":"companyIndustry","type":"text","label":"Industry"},{"name":"employmentType","type":"select","label":"Employment Type","required":true,"options":["Full-time","Part-time","Contract","Internship","Freelance","Remote","Seasonal"]},{"name":"salaryMin","type":"number","label":"Min Salary"},{"name":"salaryMax","type":"number","label":"Max Salary"},{"name":"salaryCurrency","type":"select","label":"Currency","options":["USD","IDR","AUD","EUR","GBP","SGD","MYR","PHP","THB","VND"]},{"name":"salaryPeriod","type":"select","label":"Salary Period","options":["hour","day","week","month","year"]},{"name":"salaryNegotiable","type":"boolean","label":"Salary Negotiable"},{"name":"experienceLevel","type":"select","label":"Experience Level","options":["Entry Level","Junior (1-3 years)","Mid Level (3-5 years)","Senior (5-10 years)","Lead/Manager","Executive"]},{"name":"educationLevel","type":"select","label":"Education Required","options":["High School","Diploma","Bachelor'"'"'s Degree","Master'"'"'s Degree","PhD","Any"]},{"name":"qualifications","type":"textarea","label":"Qualifications Required"},{"name":"skills","type":"multi-select","label":"Skills Required","options":["Communication","Leadership","Problem Solving","Teamwork","Adaptability","Time Management","Technical Writing","Project Management","Data Analysis","Customer Service"]},{"name":"jobDescription","type":"textarea","label":"Job Description"},{"name":"responsibilities","type":"textarea","label":"Key Responsibilities"},{"name":"benefits","type":"textarea","label":"Benefits & Perks"},{"name":"location","type":"text","label":"Work Location","required":true},{"name":"city","type":"text","label":"City"},{"name":"remoteAllowed","type":"boolean","label":"Remote/Hybrid Allowed"},{"name":"travelRequired","type":"boolean","label":"Travel Required"},{"name":"applicationDeadline","type":"date","label":"Application Deadline"},{"name":"startDate","type":"date","label":"Start Date"},{"name":"contactName","type":"text","label":"Contact Person"},{"name":"contactEmail","type":"email","label":"Contact Email","required":true},{"name":"contactPhone","type":"text","label":"Contact Phone"},{"name":"applicationUrl","type":"url","label":"Apply Online URL"},{"name":"images","type":"images","label":"Company/Office Photos","max":5}]'),
('services', 'Services', 'services', 'Professional and personal services', '🔧', NULL, 5, 1, '[{"name":"serviceName","type":"text","label":"Service/Business Name","required":true},{"name":"serviceType","type":"select","label":"Service Category","required":true,"options":["Professional","Home","Beauty","Education","Events","Transport","Pet","Other"]},{"name":"pricingType","type":"select","label":"Pricing Type","required":true,"options":["Fixed Price","Hourly Rate","Daily Rate","Per Project","Starting From","Negotiable","Free"]},{"name":"price","type":"number","label":"Price","min":0},{"name":"priceCurrency","type":"select","label":"Currency","options":["USD","IDR","AUD","EUR","GBP","SGD"]},{"name":"priceIncludes","type":"textarea","label":"Price Includes"},{"name":"serviceArea","type":"text","label":"Service Area/Coverage"},{"name":"remoteAvailable","type":"boolean","label":"Remote/Online Available"},{"name":"availability","type":"select","label":"Availability","options":["Available Now","By Appointment","Weekdays Only","Weekends Only","Evenings Only","Flexible"]},{"name":"workingHours","type":"text","label":"Working Hours"},{"name":"responseTime","type":"select","label":"Response Time","options":["Within 1 hour","Within 24 hours","Within 3 days","Within 1 week"]},{"name":"description","type":"textarea","label":"Service Description"},{"name":"experience","type":"number","label":"Years of Experience"},{"name":"qualifications","type":"textarea","label":"Qualifications/Certifications"},{"name":"portfolio","type":"url","label":"Portfolio/Website URL"},{"name":"insured","type":"boolean","label":"Fully Insured"},{"name":"bonded","type":"boolean","label":"Bonded"},{"name":"homeVisit","type":"boolean","label":"Home Visit Available"},{"name":"emergencyService","type":"boolean","label":"Emergency Service"},{"name":"rushJobAvailable","type":"boolean","label":"Rush Job Available"},{"name":"contactName","type":"text","label":"Contact Person"},{"name":"contactPhone","type":"text","label":"Phone"},{"name":"contactWhatsApp","type":"text","label":"WhatsApp"},{"name":"contactEmail","type":"email","label":"Email"},{"name":"rating","type":"number","label":"Average Rating","min":0,"max":5},{"name":"reviewCount","type":"number","label":"Number of Reviews"},{"name":"images","type":"images","label":"Service Photos","max":12}]'),
('rentals', 'Rentals', 'rentals', 'Property and equipment for rent', '🔑', NULL, 6, 1, '[{"name":"rentalType","type":"select","label":"Property Type","required":true,"options":["Apartment","House","Room","Office","Shop","Warehouse","Vacation","Land","Other"]},{"name":"rentAmount","type":"number","label":"Rent Amount","required":true,"min":0},{"name":"rentCurrency","type":"select","label":"Currency","options":["USD","IDR","AUD","EUR","GBP","SGD"]},{"name":"rentPeriod","type":"select","label":"Rent Period","required":true,"options":["day","week","month","year"]},{"name":"bondAmount","type":"number","label":"Bond/Security Deposit"},{"name":"bondMonths","type":"number","label":"Bond (months)","min":0,"max":12},{"name":"billsIncluded","type":"multi-select","label":"Bills Included","options":["Electricity","Water","Internet","Gas","TV/Cable","Management Fees","None"]},{"name":"minRentalPeriod","type":"number","label":"Minimum Rental Period","min":1},{"name":"minRentalUnit","type":"select","label":"Minimum Period Unit","options":["days","weeks","months","years"]},{"name":"availableFrom","type":"date","label":"Available From","required":true},{"name":"availableTo","type":"date","label":"Available To"},{"name":"bedrooms","type":"number","label":"Bedrooms","min":0},{"name":"bathrooms","type":"number","label":"Bathrooms","min":0,"max":10},{"name":"parkingSpaces","type":"number","label":"Parking Spaces","min":0},{"name":"furnished","type":"select","label":"Furnished","options":["Unfurnished","Partially Furnished","Fully Furnished"]},{"name":"petFriendly","type":"boolean","label":"Pet Friendly"},{"name":"smokingAllowed","type":"boolean","label":"Smoking Allowed"},{"name":"amenities","type":"multi-select","label":"Amenities","options":["WiFi","Air Conditioning","Heating","Hot Water","Washing Machine","Refrigerator","TV","Gym","Pool","Security","Elevator/Lift","Garden","Balcony","Wheelchair Access"]},{"name":"location","type":"text","label":"Location/Address","required":true},{"name":"city","type":"text","label":"City"},{"name":"proximityTo","type":"text","label":"Near (schools, hospitals, etc.)"},{"name":"houseRules","type":"textarea","label":"House Rules"},{"name":"maxOccupants","type":"number","label":"Maximum Occupants","min":1},{"name":"images","type":"images","label":"Photos","max":16}]'),
('wanted', 'Wanted', 'wanted', 'Items or services people are looking for', '🔍', NULL, 7, 1, '[{"name":"wantedType","type":"select","label":"Looking For","required":true,"options":["Item","Vehicle","Property","Service","Job","Roommate","Space"]},{"name":"title","type":"text","label":"What Are You Looking For","required":true},{"name":"budgetMin","type":"number","label":"Min Budget","min":0},{"name":"budgetMax","type":"number","label":"Max Budget","min":0},{"name":"budgetCurrency","type":"select","label":"Currency","options":["USD","IDR","AUD","EUR","GBP","SGD"]},{"name":"negotiable","type":"boolean","label":"Budget Flexible"},{"name":"condition","type":"select","label":"Preferred Condition","options":["Any","New","Like New","Excellent","Good","Fair"]},{"name":"brandPreference","type":"text","label":"Brand Preference"},{"name":"modelPreference","type":"text","label":"Model/Type Preference"},{"name":"location","type":"text","label":"Preferred Location"},{"name":"willingToTravel","type":"boolean","label":"Willing to Travel"},{"name":"travelDistance","type":"text","label":"Max Travel Distance"},{"name":"urgency","type":"select","label":"Urgency","options":["Flexible","Within 1 Month","Soon","Urgent","ASAP"]},{"name":"neededBy","type":"date","label":"Needed By"},{"name":"description","type":"textarea","label":"Details/Requirements"},{"name":"images","type":"images","label":"Reference Images","max":5},{"name":"contactPreference","type":"select","label":"Contact Preference","options":["Phone","WhatsApp","Email","In Person","Any"]},{"name":"contactPhone","type":"text","label":"Phone"},{"name":"contactEmail","type":"email","label":"Email"},{"name":"contactWhatsApp","type":"text","label":"WhatsApp"}]'),
('community', 'Community', 'community', 'Events, lost & found, free items, and community activities', '🎭', NULL, 8, 1, '[{"name":"description","type":"textarea","label":"Description"}]'),
('pets-animals', 'Pets & Animals', 'pets-animals', 'Pets for sale, adoption, or looking for home', '🐾', NULL, 9, 1, '[{"name":"petType","type":"select","label":"Pet Type","required":true,"options":["Dog","Cat","Bird","Fish","Reptile","Rabbit","Hamster","Guinea Pig","Horse","Farm Animal","Other"]},{"name":"breed","type":"text","label":"Breed"},{"name":"mixedBreed","type":"boolean","label":"Mixed Breed"},{"name":"name","type":"text","label":"Name (if named)"},{"name":"age","type":"select","label":"Age","required":true,"options":["Baby (0-6 months)","Young (6-12 months)","Adult (1-8 years)","Senior (8+ years)"]},{"name":"ageMonths","type":"number","label":"Age in Months (if known)","min":0},{"name":"gender","type":"select","label":"Gender","required":true,"options":["Male","Female","Unknown"]},{"name":"size","type":"select","label":"Size","options":["Toy","Small","Medium","Large","Giant"]},{"name":"vaccinated","type":"boolean","label":"Vaccinated"},{"name":"vaccinationRecords","type":"boolean","label":"Vaccination Records Available"},{"name":"dewormed","type":"boolean","label":"Dewormed"},{"name":"spayedNeutered","type":"boolean","label":"Spayed/Neutered"},{"name":"microchipped","type":"boolean","label":"Microchipped"},{"name":"microchipNumber","type":"text","label":"Microchip Number"},{"name":"registrationPapers","type":"boolean","label":"Registration Papers Available"},{"name":"pedigree","type":"boolean","label":"Pedigree/Show Quality"},{"name":"healthIssues","type":"textarea","label":"Health Issues/Special Needs"},{"name":"listingType","type":"select","label":"Listing Type","required":true,"options":["For Sale","Free to Good Home","For Adoption","Stud Service","Lost","Found","For Hire"]},{"name":"rehomingFee","type":"number","label":"Rehoming Fee"},{"name":"reasonForRehoming","type":"textarea","label":"Reason for Rehoming"},{"name":"temperament","type":"multi-select","label":"Temperament","options":["Friendly","Shy","Playful","Calm","Energetic","Good with Kids","Good with Dogs","Good with Cats","House Trained","Crate Trained","Leash Trained"]},{"name":"specialNeeds","type":"textarea","label":"Special Needs/Requirements"},{"name":"images","type":"images","label":"Photos","max":12},{"name":"location","type":"text","label":"Location","required":true},{"name":"adoptRequirements","type":"textarea","label":"Adoption Requirements"}]'),
('agriculture', 'Agriculture', 'agriculture', 'Farm products, livestock, and agricultural equipment', '🌾', NULL, 10, 1, '[{"name":"agriType","type":"select","label":"Type","required":true,"options":["Crops","Livestock","Equipment","Seeds","Fertilizer","Fish","Other"]},{"name":"title","type":"text","label":"Title","required":true},{"name":"price","type":"number","label":"Price","required":true,"min":0},{"name":"negotiable","type":"boolean","label":"Negotiable"},{"name":"pricePerUnit","type":"text","label":"Price Per Unit"},{"name":"quantity","type":"number","label":"Total Quantity"},{"name":"unit","type":"text","label":"Unit"},{"name":"availableQuantity","type":"number","label":"Currently Available"},{"name":"quality","type":"select","label":"Quality","options":["Premium","Grade A","Grade B","Standard","For Processing"]},{"name":"organic","type":"boolean","label":"Organic/Organic Certified"},{"name":"certification","type":"text","label":"Certifications"},{"name":"soilType","type":"select","label":"Soil Type","options":["Clay","Sandy","Loamy","Silty","Peaty","Chalky","Not Applicable"]},{"name":"climateZone","type":"text","label":"Climate Zone"},{"name":"location","type":"text","label":"Farm Location"},{"name":"deliveryAvailable","type":"boolean","label":"Delivery Available"},{"name":"deliveryArea","type":"text","label":"Delivery Area"},{"name":"description","type":"textarea","label":"Description"},{"name":"images","type":"images","label":"Photos","max":12}]');

-- VEHICLES SUB-CATEGORIES (9)
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('cars-suvs', 'Cars & SUVs', 'cars-suvs', 'Cars and passenger vehicles', '🚙', 'vehicles', 11, 1, '[{"name":"bodyType","type":"select","label":"Body Type","options":["Sedan","SUV","Hatchback","Coupe","Wagon","Convertible","Van","Truck","Pickup","Minivan"]},{"name":"engineSize","type":"text","label":"Engine Size (L)"},{"name":"drivetrain","type":"select","label":"Drivetrain","options":["FWD","RWD","4WD","AWD"]},{"name":"seatingCapacity","type":"number","label":"Seating Capacity","min":1,"max":15},{"name":"fuelEfficiency","type":"text","label":"Fuel Efficiency (L/100km)"}]'),
('motorcycles', 'Motorcycles & Scooters', 'motorcycles', 'Motorcycles and scooters', '🏍️', 'vehicles', 12, 1, '[{"name":"engineSize_cc","type":"number","label":"Engine Size (cc)","min":50},{"name":"helmetIncluded","type":"boolean","label":"Helmet Included"},{"name":"helmetCount","type":"number","label":"Number of Helmets","min":0},{"name":"licensePlate","type":"text","label":"License Plate"},{"name":"motorcycleType","type":"select","label":"Type","options":["Sport","Cruiser","Touring","Adventure","Naked","Scooter","Moped","Dirt Bike","Cafe Racer"]}]'),
('bicycles', 'Bicycles', 'bicycles', 'Bicycles of all types', '🚲', 'vehicles', 13, 1, '[{"name":"bicycleType","type":"select","label":"Bicycle Type","options":["Mountain","Road","Hybrid","BMX","Kids","Electric","Folding","Cargo"]},{"name":"frameSize","type":"text","label":"Frame Size"},{"name":"suspension","type":"select","label":"Suspension","options":["None","Front","Full"]},{"name":"brakes","type":"select","label":"Brakes","options":["Disc","V-Brake","Coaster","Hydraulic"]},{"name":"gearCount","type":"number","label":"Number of Gears"}]'),
('vans-trucks', 'Vans & Trucks', 'vans-trucks', 'Commercial vehicles and trucks', '🚚', 'vehicles', 14, 1, '[{"name":"loadCapacity","type":"number","label":"Load Capacity (kg)"},{"name":"cabType","type":"select","label":"Cab Type","options":["Regular","Extended","Crew"]},{"name":"numberOfSeats","type":"number","label":"Number of Seats","min":1,"max":15},{"name":"bedLength","type":"text","label":"Bed/Load Area Length (m)"},{"name":"boxType","type":"select","label":"Box Type","options":["Open","Closed","Refrigerated","Flatbed"]}]'),
('boats-marine', 'Boats & Marine', 'boats-marine', 'Boats, yachts, and marine equipment', '⛵', 'vehicles', 15, 1, '[{"name":"length","type":"number","label":"Length (m)"},{"name":"boatType","type":"select","label":"Boat Type","options":["Sailboat","Motorboat","Yacht","Jet Ski","Fishing Boat","Pontoon","Kayak/Canoe","Inflatable"]},{"name":"hullMaterial","type":"select","label":"Hull Material","options":["Fiberglass","Aluminum","Wood","Steel","Inflatable"]},{"name":"engineType","type":"select","label":"Engine Type","options":["Outboard","Inboard","None"]},{"name":"enginePower","type":"text","label":"Engine Power (HP)"},{"name":"capacity","type":"number","label":"Max Capacity (persons)"}]'),
('rvs-campers', 'RVs & Campers', 'rvs-campers', 'Recreational vehicles and campers', '🚐', 'vehicles', 16, 1, '[{"name":"sleepingCapacity","type":"number","label":"Sleeping Capacity","min":1},{"name":"bathrooms","type":"number","label":"Number of Bathrooms","min":0},{"name":"hasKitchen","type":"boolean","label":"Kitchen Available"},{"name":"yearBuilt","type":"number","label":"Year Built","min":1970,"max":2027},{"name":"slideouts","type":"number","label":"Number of Slideouts","min":0},{"name":"rvType","type":"select","label":"RV Type","options":["Class A","Class B","Class C","Travel Trailer","Fifth Wheel","Pop-up Camper","Truck Camper"]}]'),
('vehicle-parts', 'Parts & Accessories', 'vehicle-parts', 'Vehicle parts and accessories', '⚙️', 'vehicles', 17, 1, '[{"name":"partType","type":"select","label":"Part Type","options":["Engine","Transmission","Suspension","Brakes","Electrical","Interior","Exterior","Wheels/Tires","Audio/Electronics","Other"]},{"name":"compatibleMake","type":"text","label":"Compatible Make(s)"},{"name":"compatibleModel","type":"text","label":"Compatible Model(s)"},{"name":"newUsed","type":"select","label":"Condition","options":["New","Used - Like New","Used - Good","Used - Fair","Refurbished"]},{"name":"warrantyPeriod","type":"text","label":"Warranty Period"},{"name":"partNumber","type":"text","label":"Part Number"}]'),
('agri-vehicles', 'Agricultural Vehicles', 'agri-vehicles', 'Tractors and farm vehicles', '🚜', 'vehicles', 18, 1, '[{"name":"horsepower","type":"number","label":"Horsepower (HP)"},{"name":"hoursUsed","type":"number","label":"Hours Used"},{"name":"implementsIncluded","type":"boolean","label":"Implements Included"},{"name":"drivetrain","type":"select","label":"Drivetrain","options":["2WD","4WD"]},{"name":"ptoHp","type":"number","label":"PTO Horsepower"},{"name":"threePointHitch","type":"boolean","label":"3-Point Hitch"}]'),
('other-vehicles', 'Other Vehicles', 'other-vehicles', 'Other types of vehicles', '🛺', 'vehicles', 19, 1, '[{"name":"vehicleType","type":"text","label":"Vehicle Type"}]');

-- PROPERTY SALE SUB-CATEGORIES (8)
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('houses-villas', 'Houses & Villas', 'houses-villas', 'Houses and villas for sale', '🏡', 'property-sale', 21, 1, '[]'),
('apartments-condos', 'Apartments & Condos', 'apartments-condos', 'Apartments and condos for sale', '🏢', 'property-sale', 22, 1, '[{"name":"floorLevel","type":"number","label":"Floor Level"},{"name":"totalFloors","type":"number","label":"Total Floors"},{"name":"hasLift","type":"boolean","label":"Has Elevator/Lift"}]'),
('townhouses', 'Townhouses', 'townhouses', 'Townhouses for sale', '🏘️', 'property-sale', 23, 1, '[{"name":"totalUnits","type":"number","label":"Total Units in Complex"},{"name":"communityFees","type":"number","label":"Community Fees"}]'),
('duplexes', 'Duplexes', 'duplexes', 'Duplexes for sale', '🏠', 'property-sale', 24, 1, '[{"name":"separateEntrances","type":"number","label":"Number of Separate Entrances"}]'),
('land-plots', 'Land & Plots', 'land-plots', 'Land and plots for sale', '🏔️', 'property-sale', 25, 1, '[{"name":"landType","type":"select","label":"Land Type","options":["Residential","Commercial","Agricultural","Industrial","Mixed Use"]},{"name":"zoning","type":"text","label":"Zoning Classification"},{"name":"roadAccess","type":"select","label":"Road Access","options":["Paved Road","Dirt Road","No Direct Access","Shared Access"]},{"name":"waterAccess","type":"boolean","label":"Water Access"},{"name":"electricityAccess","type":"boolean","label":"Electricity Access"},{"name":"floodRisk","type":"select","label":"Flood Risk","options":["None","Low","Medium","High","Unknown"]}]'),
('commercial-buildings', 'Commercial Buildings', 'commercial-buildings', 'Commercial properties for sale', '🏬', 'property-sale', 26, 1, '[{"name":"businessType","type":"select","label":"Suitable For","options":["Retail","Office","Restaurant","Hotel","Warehouse","Medical","Educational","Entertainment"]},{"name":"floorCount","type":"number","label":"Number of Floors"},{"name":"elevatorAvailable","type":"boolean","label":"Elevator Available"},{"name":"parkingSpaces","type":"number","label":"Parking Spaces"},{"name":"operatingBusiness","type":"boolean","label":"Currently Operating Business"}]'),
('industrial-buildings', 'Industrial Buildings', 'industrial-buildings', 'Industrial properties for sale', '🏭', 'property-sale', 27, 1, '[{"name":"workshopSpace","type":"number","label":"Workshop Space (m²)"},{"name":"officeSpace","type":"number","label":"Office Space (m²)"},{"name":"loadingBay","type":"boolean","label":"Loading Bay Available"},{"name":"craneCapacity","type":"text","label":"Crane Capacity (tons)"},{"name":"clearHeight","type":"number","label":"Clear Height (m)"},{"name":"floorLoading","type":"text","label":"Floor Loading Capacity"}]'),
('other-property', 'Other Property', 'other-property', 'Other types of property for sale', '🏗️', 'property-sale', 28, 1, '[]');

-- FOR SALE SUB-CATEGORIES (12)
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('electronics', 'Electronics & Gadgets', 'electronics', 'Phones, computers, and gadgets', '📱', 'for-sale', 31, 1, '[{"name":"storage","type":"text","label":"Storage Capacity (GB/TB)"},{"name":"ram","type":"text","label":"RAM (GB)"},{"name":"screenSize","type":"text","label":"Screen Size"},{"name":"networkType","type":"select","label":"Network","options":["WiFi Only","WiFi + Cellular","4G","5G"]},{"name":"batteryHealth","type":"number","label":"Battery Health (%)","min":0,"max":100},{"name":"operatingSystem","type":"select","label":"Operating System","options":["iOS","Android","Windows","macOS","Linux","Not Applicable"]},{"name":"accessoriesIncluded","type":"multi-select","label":"Accessories Included","options":["Charger","Cable","Case","Earbuds","Manual","Original Box"]}]'),
('fashion', 'Fashion & Accessories', 'fashion', 'Clothing, shoes, and accessories', '👗', 'for-sale', 32, 1, '[{"name":"gender","type":"select","label":"Gender","options":["Men","Women","Unisex","Boys","Girls","Kids"]},{"name":"clothingSize","type":"text","label":"Clothing Size"},{"name":"shoeSize","type":"text","label":"Shoe Size (EU/US/UK)"},{"name":"waistSize","type":"text","label":"Waist Size"},{"name":"chestSize","type":"text","label":"Chest Size"},{"name":"material","type":"text","label":"Material/Fabric"},{"name":"designer","type":"text","label":"Designer/Brand"},{"name":"authentic","type":"boolean","label":"Authentic/Original"}]'),
('home-garden', 'Home & Garden', 'home-garden', 'Home and garden items', '🪴', 'for-sale', 33, 1, '[{"name":"furnitureType","type":"select","label":"Furniture Type","options":["Sofa","Bed","Table","Chair","Cabinet","Desk","Storage","Outdoor","Other"]},{"name":"roomType","type":"select","label":"Room Type","options":["Living Room","Bedroom","Kitchen","Bathroom","Office","Outdoor","Other"]},{"name":"style","type":"select","label":"Style","options":["Modern","Traditional","Vintage","Minimalist","Industrial","Bohemian","Scandinavian","Other"]},{"name":"material","type":"text","label":"Material"},{"name":"dimensions","type":"text","label":"Dimensions (L x W x H cm)"}]'),
('sports-outdoors', 'Sports & Outdoors', 'sports-outdoors', 'Sports gear and outdoor equipment', '⚽', 'for-sale', 34, 1, '[{"name":"sportType","type":"select","label":"Sport/Activity","options":["Football","Basketball","Tennis","Swimming","Cycling","Gym/Fitness","Hiking","Camping","Water Sports","Winter Sports","Martial Arts","Other"]},{"name":"usedFor","type":"select","label":"Used For","options":["Indoor","Outdoor","Both"]},{"name":"skillLevel","type":"select","label":"Skill Level","options":["Beginner","Intermediate","Advanced","Professional"]}]'),
('baby-kids', 'Baby & Kids', 'baby-kids', 'Baby and kids items', '👶', 'for-sale', 35, 1, '[{"name":"ageRange","type":"select","label":"Age Range","options":["0-6 months","6-12 months","1-2 years","2-4 years","4-6 years","6-8 years","8-12 years","12+ years"]},{"name":"gender","type":"select","label":"Gender","options":["Boys","Girls","Unisex"]},{"name":"safetyCertified","type":"boolean","label":"Safety Certified"}]'),
('books-education', 'Books & Education', 'books-education', 'Books, textbooks, and educational materials', '📚', 'for-sale', 36, 1, '[{"name":"bookFormat","type":"select","label":"Format","options":["Hardcover","Paperback","E-Book","Audiobook"]},{"name":"genre","type":"text","label":"Genre/Subject"},{"name":"author","type":"text","label":"Author"},{"name":"isbn","type":"text","label":"ISBN"},{"name":"condition","type":"select","label":"Condition","options":["New","Like New","Good","Fair","Poor"]}]'),
('health-beauty', 'Health & Beauty', 'health-beauty', 'Health and beauty products', '💄', 'for-sale', 37, 1, '[{"name":"skinType","type":"select","label":"Skin Type","options":["Normal","Dry","Oily","Combination","Sensitive","All Skin Types"]},{"name":"brand","type":"text","label":"Brand"},{"name":"expiryDate","type":"date","label":"Expiry Date"},{"name":"organic","type":"boolean","label":"Organic/Natural"},{"name":"sealed","type":"boolean","label":"Sealed/Unopened"}]'),
('office-business', 'Office & Business', 'office-business', 'Office equipment and business supplies', '💼', 'for-sale', 38, 1, '[{"name":"businessType","type":"select","label":"Business Type","options":["Office Furniture","Office Equipment","Point of Sale","Restaurant Equipment","Medical Equipment","Industrial Equipment","Other"]}]'),
('industrial-equipment', 'Industrial Equipment', 'industrial-equipment', 'Industrial and commercial equipment', '🏗️', 'for-sale', 39, 1, '[{"name":"operatingCondition","type":"select","label":"Condition","options":["New","Like New","Good","Fair","Needs Repair","For Parts"]},{"name":"voltage","type":"text","label":"Voltage/Power"},{"name":"powerRating","type":"text","label":"Power Rating"},{"name":"certification","type":"text","label":"Certification/Standard"}]'),
('musical-instruments', 'Musical Instruments', 'musical-instruments', 'Musical instruments and equipment', '🎸', 'for-sale', 40, 1, '[{"name":"instrumentType","type":"select","label":"Instrument Type","options":["Guitar","Piano/Keyboard","Drums","Violin","Saxophone","Trumpet","Flute","Other"]},{"name":"isElectric","type":"boolean","label":"Electric/Acoustic"},{"name":"caseIncluded","type":"boolean","label":"Case Included"},{"name":"ampIncluded","type":"boolean","label":"Amplifier Included"},{"name":"age","type":"text","label":"Age of Instrument"},{"name":"modifications","type":"text","label":"Modifications/Upgrades"}]'),
('art-antiques', 'Art & Antiques', 'art-antiques', 'Art, antiques, and collectibles', '🎨', 'for-sale', 41, 1, '[{"name":"artType","type":"select","label":"Art Type","options":["Painting","Sculpture","Photography","Print","Drawing","Digital Art","Antique","Collectible","Handcraft","Jewelry","Other"]},{"name":"period","type":"text","label":"Period/Era"},{"name":"artist","type":"text","label":"Artist/Creator"},{"name":"dimensions","type":"text","label":"Dimensions"},{"name":"authenticity","type":"select","label":"Authenticity","options":["Original","Limited Edition","Print/Reproduction","Vintage Copy","Unknown"]}]'),
('other-items', 'Other Items', 'other-items', 'Other items for sale', '📦', 'for-sale', 42, 1, '[]');

-- JOBS SUB-CATEGORIES (7)
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('full-time', 'Full-time', 'full-time', 'Full-time employment', '💼', 'jobs', 51, 1, '[]'),
('part-time', 'Part-time', 'part-time', 'Part-time employment', '⏰', 'jobs', 52, 1, '[]'),
('contract', 'Contract', 'contract', 'Contract employment', '📝', 'jobs', 53, 1, '[]'),
('internship', 'Internship', 'internship', 'Internship positions', '🎓', 'jobs', 54, 1, '[]'),
('freelance', 'Freelance', 'freelance', 'Freelance opportunities', '💻', 'jobs', 55, 1, '[]'),
('remote', 'Remote / Work from Home', 'remote', 'Remote and work-from-home jobs', '🏠', 'jobs', 56, 1, '[]'),
('seasonal', 'Seasonal / Temporary', 'seasonal', 'Seasonal and temporary positions', '❄️', 'jobs', 57, 1, '[]');

-- SERVICES SUB-CATEGORIES (8)
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('professional-services', 'Professional Services', 'professional-services', 'Legal, accounting, consulting', '💼', 'services', 61, 1, '[{"name":"qualificationCert","type":"text","label":"Professional License/Certification"},{"name":"yearsInBusiness","type":"number","label":"Years in Business"},{"name":"insurance","type":"boolean","label":"Professional Liability Insurance"}]'),
('home-services', 'Home Services', 'home-services', 'Repair, cleaning, maintenance', '🔧', 'services', 62, 1, '[{"name":"serviceRadius","type":"number","label":"Service Radius (km)"},{"name":"toolsIncluded","type":"boolean","label":"Tools & Materials Included"},{"name":"cleanupIncluded","type":"boolean","label":"Cleanup Included"}]'),
('beauty-wellness', 'Beauty & Wellness', 'beauty-wellness', 'Hair, makeup, spa, massage', '💆', 'services', 63, 1, '[{"name":"licensed","type":"boolean","label":"Licensed/Certified"},{"name":"yearsExperience","type":"number","label":"Years of Experience"}]'),
('education-training', 'Education & Training', 'education-training', 'Tutoring, lessons, training', '📚', 'services', 64, 1, '[{"name":"teachingMode","type":"select","label":"Teaching Mode","options":["In Person","Online","Both"]},{"name":"hourlyRate","type":"number","label":"Hourly Rate"},{"name":"qualifications","type":"text","label":"Qualifications"}]'),
('events-entertainment', 'Events & Entertainment', 'events-entertainment', 'Photography, DJ, event planning', '🎤', 'services', 65, 1, '[{"name":"eventType","type":"multi-select","label":"Event Types","options":["Wedding","Birthday","Corporate","Concert","Conference","Private Party","Other"]},{"name":"equipment","type":"text","label":"Equipment Available"}]'),
('transport-logistics', 'Transport & Logistics', 'transport-logistics', 'Moving, delivery, taxi', '🚛', 'services', 66, 1, '[{"name":"vehicleTypes","type":"multi-select","label":"Vehicle Types","options":["Car","Van","Truck","Motorcycle","Bicycle","Other"]},{"name":"serviceArea","type":"text","label":"Service Area"}]'),
('pet-services', 'Pet Services', 'pet-services', 'Pet sitting, grooming, vet', '🐕', 'services', 67, 1, '[{"name":"petTypes","type":"multi-select","label":"Pet Types","options":["Dogs","Cats","Birds","Fish","Reptiles","Small Pets","All Pets"]},{"name":"serviceType","type":"multi-select","label":"Services","options":["Grooming","Boarding","Day Care","Walking","Training","Veterinary","Other"]}]'),
('other-services', 'Other Services', 'other-services', 'Other services', '🛠️', 'services', 68, 1, '[]');

-- RENTALS SUB-CATEGORIES (9)
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('apartments-flats', 'Apartments & Flats', 'apartments-flats', 'Apartments and flats for rent', '🏢', 'rentals', 71, 1, '[{"name":"floorLevel","type":"number","label":"Floor Level"},{"name":"totalFloors","type":"number","label":"Total Floors in Building"}]'),
('houses-villas-rental', 'Houses & Villas', 'houses-villas-rental', 'Houses and villas for rent', '🏡', 'rentals', 72, 1, '[{"name":"gardenSize","type":"number","label":"Garden Size (m²)"}]'),
('rooms', 'Rooms', 'rooms', 'Rooms for rent', '🛏️', 'rentals', 73, 1, '[{"name":"roommateCount","type":"number","label":"Current Roommates"},{"name":"furnished","type":"select","label":"Furnished","options":["Unfurnished","Partially Furnished","Fully Furnished"]}]'),
('offices', 'Offices', 'offices', 'Office space for rent', '🏢', 'rentals', 74, 1, '[{"name":"floorLevel","type":"number","label":"Floor Level"},{"name":"totalFloors","type":"number","label":"Total Floors in Building"},{"name":"workspaceArea","type":"number","label":"Workspace Area (m²)"},{"name":"meetingRooms","type":"number","label":"Meeting Rooms"},{"name":"receptionist","type":"boolean","label":"Receptionist Service"},{"name":"internetIncluded","type":"boolean","label":"Internet Included"},{"name":"phoneSystem","type":"boolean","label":"Phone System Available"}]'),
('shops-retail', 'Shops & Retail Space', 'shops-retail', 'Retail space for rent', '🏪', 'rentals', 75, 1, '[{"name":"shopFront","type":"text","label":"Shop Front Width (m)"},{"name":"storageArea","type":"number","label":"Storage Area (m²)"},{"name":"licenseIncluded","type":"boolean","label":"Business License Included"},{"name":"peakHours","type":"text","label":"Peak Trading Hours"}]'),
('warehouses-storage', 'Warehouses & Storage', 'warehouses-storage', 'Warehouses and storage space', '📦', 'rentals', 76, 1, '[{"name":"clearHeight","type":"number","label":"Clear Height (m)"},{"name":"securitySystem","type":"boolean","label":"Security System"},{"name":"loadingDock","type":"boolean","label":"Loading Dock"}]'),
('vacation-rentals', 'Vacation Rentals', 'vacation-rentals', 'Short-term vacation rentals', '🏖️', 'rentals', 77, 1, '[{"name":"minStay","type":"number","label":"Minimum Stay (nights)","min":1},{"name":"maxGuests","type":"number","label":"Maximum Guests","min":1},{"name":"checkInTime","type":"text","label":"Check-in Time"},{"name":"checkOutTime","type":"text","label":"Check-out Time"},{"name":"poolAccess","type":"boolean","label":"Pool Access"},{"name":"beachAccess","type":"boolean","label":"Beach Access"},{"name":"cleaningFee","type":"number","label":"Cleaning Fee"},{"name":"cancellationPolicy","type":"select","label":"Cancellation Policy","options":["Flexible","Moderate","Strict","Non-refundable"]}]'),
('land-rental', 'Land', 'land-rental', 'Land for rent', '🏔️', 'rentals', 78, 1, '[{"name":"landUseType","type":"select","label":"Land Use","options":["Agricultural","Commercial","Industrial","Recreational"]}]'),
('other-rentals', 'Other Rentals', 'other-rentals', 'Other rentals', '🏠', 'rentals', 79, 1, '[]');

-- WANTED SUB-CATEGORIES (7)
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('items-wanted', 'Items Wanted', 'items-wanted', 'Items you are looking for', '🛍️', 'wanted', 81, 1, '[]'),
('vehicles-wanted', 'Vehicles Wanted', 'vehicles-wanted', 'Vehicles you are looking for', '🚗', 'wanted', 82, 1, '[]'),
('property-wanted', 'Property Wanted', 'property-wanted', 'Property you are looking for', '🏠', 'wanted', 83, 1, '[]'),
('services-needed', 'Services Needed', 'services-needed', 'Services you are looking for', '🔧', 'wanted', 84, 1, '[]'),
('jobs-wanted', 'Jobs Wanted', 'jobs-wanted', 'Job opportunities you are looking for', '💼', 'wanted', 85, 1, '[]'),
('roommate-wanted', 'Roommate Wanted', 'roommate-wanted', 'Looking for a roommate', '👥', 'wanted', 86, 1, '[]'),
('space-wanted', 'Space Wanted', 'space-wanted', 'Space you are looking for', '📍', 'wanted', 87, 1, '[]');

-- COMMUNITY SUB-CATEGORIES (7)
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('events-activities', 'Events & Activities', 'events-activities', 'Concerts, workshops, and community events', '🎭', 'community', 91, 1, '[{"name":"eventName","type":"text","label":"Event Name","required":true},{"name":"eventType","type":"select","label":"Event Type","required":true,"options":["Concert/Performance","Workshop/Class","Conference/Seminar","Festival/Fair","Sports Event","Community Meetup","Market/Bazaar","Exhibition","Other"]},{"name":"eventDate","type":"date","label":"Event Date","required":true},{"name":"eventTime","type":"text","label":"Start Time"},{"name":"eventEndDate","type":"date","label":"End Date"},{"name":"duration","type":"text","label":"Duration"},{"name":"recurring","type":"select","label":"Recurring","options":["One-time","Daily","Weekly","Bi-weekly","Monthly"]},{"name":"venue","type":"text","label":"Venue/Location","required":true},{"name":"city","type":"text","label":"City"},{"name":"virtualEvent","type":"boolean","label":"Virtual/Online Event"},{"name":"meetingLink","type":"url","label":"Virtual Meeting Link"},{"name":"ticketRequired","type":"boolean","label":"Ticket Required"},{"name":"ticketPrice","type":"number","label":"Ticket Price","min":0},{"name":"freeEntry","type":"boolean","label":"Free Entry"},{"name":"ticketsAvailable","type":"number","label":"Tickets Available"},{"name":"organizerName","type":"text","label":"Organizer"},{"name":"organizerContact","type":"text","label":"Organizer Contact"},{"name":"ageRestriction","type":"text","label":"Age Restriction"},{"name":"dressCode","type":"text","label":"Dress Code"},{"name":"description","type":"textarea","label":"Event Description"},{"name":"images","type":"images","label":"Event Images","max":8}]'),
('lost-found', 'Lost & Found', 'lost-found', 'Lost and found items', '🔎', 'community', 92, 1, '[{"name":"itemType","type":"select","label":"Type","required":true,"options":["Lost Item","Found Item","Lost Pet"]},{"name":"category","type":"text","label":"Item Category"},{"name":"lostDate","type":"date","label":"Lost Date"},{"name":"foundDate","type":"date","label":"Found Date"},{"name":"location","type":"text","label":"Location","required":true},{"name":"color","type":"text","label":"Color"},{"name":"brand","type":"text","label":"Brand"},{"name":"distinguishingFeatures","type":"textarea","label":"Distinguishing Features"},{"name":"reward","type":"boolean","label":"Reward Offered"},{"name":"rewardAmount","type":"number","label":"Reward Amount"},{"name":"description","type":"textarea","label":"Description"},{"name":"images","type":"images","label":"Photos","max":5},{"name":"contactPhone","type":"text","label":"Contact Phone"},{"name":"contactEmail","type":"email","label":"Contact Email"}]'),
('free-items', 'Free Items', 'free-items', 'Items for free', '🎁', 'community', 93, 1, '[{"name":"category","type":"select","label":"Category","options":["Furniture","Electronics","Clothing","Books","Kitchen","Garden","Baby Items","Sports","Other"]},{"name":"condition","type":"select","label":"Condition","options":["New","Like New","Good","Fair","Poor"]},{"name":"pickupOnly","type":"boolean","label":"Pickup Only"},{"name":"location","type":"text","label":"Location"}]'),
('volunteers-charity', 'Volunteers & Charity', 'volunteers-charity', 'Volunteer opportunities and charity', '❤️', 'community', 94, 1, '[{"name":"organizationName","type":"text","label":"Organization Name"},{"name":"volunteerType","type":"multi-select","label":"Volunteer Type","options":["On-site","Remote","Both"]},{"name":"timeCommitment","type":"text","label":"Time Commitment"},{"name":"description","type":"textarea","label":"Description"}]'),
('announcements', 'Announcements', 'announcements', 'Public announcements', '📢', 'community', 95, 1, '[{"name":"announcementType","type":"select","label":"Type","options":["Public Notice","Community News","Government","Business","Personal"]},{"name":"validUntil","type":"date","label":"Valid Until"}]'),
('discussion-groups', 'Discussion Groups', 'discussion-groups', 'Discussion groups and forums', '💬', 'community', 96, 1, '[{"name":"groupType","type":"select","label":"Group Type","options":["Buy/Sell Group","Interest Group","Neighborhood","Professional","Support Group","Other"]},{"name":"meetingFrequency","type":"text","label":"Meeting Frequency"}]'),
('other-community', 'Other Community', 'other-community', 'Other community posts', '🌐', 'community', 97, 1, '[]');

-- PETS & ANIMALS SUB-CATEGORIES (10)
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('dogs', 'Dogs', 'dogs', 'Dogs for sale or adoption', '🐕', 'pets-animals', 101, 1, '[{"name":"breed","type":"text","label":"Breed"},{"name":"registrationPapers","type":"boolean","label":"Registration Papers"}]'),
('cats', 'Cats', 'cats', 'Cats for sale or adoption', '🐈', 'pets-animals', 102, 1, '[{"name":"breed","type":"text","label":"Breed"},{"name":"indoorOutdoor","type":"select","label":"Indoor/Outdoor","options":["Indoor","Outdoor","Both"]}]'),
('birds', 'Birds', 'birds', 'Birds for sale or adoption', '🦜', 'pets-animals', 103, 1, '[{"name":"species","type":"text","label":"Species"},{"name":"talkingAbility","type":"boolean","label":"Can Talk"}]'),
('fish-aquariums', 'Fish & Aquariums', 'fish-aquariums', 'Fish and aquarium equipment', '🐠', 'pets-animals', 104, 1, '[{"name":"tankSize","type":"text","label":"Tank Size (gallons)"},{"name":"fishSpecies","type":"text","label":"Fish Species"}]'),
('reptiles', 'Reptiles & Amphibians', 'reptiles', 'Reptiles and amphibians', '🦎', 'pets-animals', 105, 1, '[{"name":"species","type":"text","label":"Species"},{"name":"habitatType","type":"text","label":"Habitat Type"}]'),
('small-pets', 'Small Pets', 'small-pets', 'Rabbits, hamsters, guinea pigs', '🐹', 'pets-animals', 106, 1, '[{"name":"species","type":"text","label":"Species"}]'),
('horses-ponies', 'Horses & Ponies', 'horses-ponies', 'Horses and ponies', '🐴', 'pets-animals', 107, 1, '[{"name":"registered","type":"boolean","label":"Registered"},{"name":"trainingLevel","type":"select","label":"Training Level","options":["Unbroken","Green","Intermediate","Advanced","School Master"]}]'),
('farm-animals', 'Farm Animals', 'farm-animals', 'Cattle, sheep, goats, etc.', '🐄', 'pets-animals', 108, 1, '[{"name":"purpose","type":"select","label":"Purpose","options":["Meat","Dairy","Breeding","Wool","Guard","Pet"]},{"name":"registrationPapers","type":"boolean","label":"Registration Papers"}]'),
('pet-supplies', 'Pet Supplies & Accessories', 'pet-supplies', 'Pet food, toys, accessories', '🦴', 'pets-animals', 109, 1, '[{"name":"petType","type":"select","label":"For Pet Type","options":["Dog","Cat","Bird","Fish","Reptile","Small Pet","All Pets"]},{"name":"productType","type":"select","label":"Product Type","options":["Food","Toys","Bedding","Grooming","Health","Accessories","Equipment"]}]'),
('pet-services', 'Pet Services', 'pet-services', 'Grooming, boarding, training', '✂️', 'pets-animals', 110, 1, '[{"name":"serviceType","type":"multi-select","label":"Services Offered","options":["Grooming","Boarding","Day Care","Walking","Training","Veterinary","Pet Sitting","Other"]}]');

-- AGRICULTURE SUB-CATEGORIES (7)
INSERT INTO listing_categories (id, name, slug, description, icon, parent_id, sort_order, is_active, form_fields) VALUES
('crops-produce', 'Crops & Produce', 'crops-produce', 'Crops and agricultural produce', '🌾', 'agriculture', 111, 1, '[{"name":"cropType","type":"text","label":"Crop Type"},{"name":"harvestDate","type":"date","label":"Harvest Date"},{"name":"plantingDate","type":"date","label":"Planting Date"},{"name":"expectedYield","type":"text","label":"Expected Yield"},{"name":"irrigationType","type":"select","label":"Irrigation","options":["Rain-fed","Drip","Sprinkler","Flood","Manual"]},{"name":"pesticideFree","type":"boolean","label":"Pesticide Free"},{"name":"packaging","type":"text","label":"Packaging Type"}]'),
('livestock-poultry', 'Livestock & Poultry', 'livestock-poultry', 'Livestock and poultry', '🐔', 'agriculture', 112, 1, '[{"name":"animalType","type":"text","label":"Animal Type"},{"name":"breed","type":"text","label":"Breed"},{"name":"gender","type":"select","label":"Gender","options":["Male","Female","Mixed"]},{"name":"age","type":"text","label":"Age"},{"name":"weight","type":"number","label":"Weight (kg)"},{"name":"vaccinated","type":"boolean","label":"Vaccinated"},{"name":"healthCertificate","type":"boolean","label":"Health Certificate"}]'),
('farm-equipment', 'Farm Equipment', 'farm-equipment', 'Tractors, harvesters, tools', '🚜', 'agriculture', 113, 1, '[{"name":"brand","type":"text","label":"Brand"},{"name":"model","type":"text","label":"Model"},{"name":"year","type":"number","label":"Year","min":1950},{"name":"hoursUsed","type":"number","label":"Hours Used"},{"name":"operatingCondition","type":"select","label":"Condition","options":["New","Like New","Good","Fair","Needs Repair","For Parts"]},{"name":"warranty","type":"boolean","label":"Warranty Available"},{"name":"sparePartsAvailable","type":"boolean","label":"Spare Parts Available"},{"name":"deliveryAvailable","type":"boolean","label":"Delivery Available"}]'),
('seeds-plants', 'Seeds & Plants', 'seeds-plants', 'Seeds, seedlings, and plants', '🌱', 'agriculture', 114, 1, '[{"name":"seedType","type":"text","label":"Seed/Plant Type"},{"name":"germinationRate","type":"number","label":"Germination Rate (%)"},{"name":"purity","type":"number","label":"Purity (%)"},{"name":"origin","type":"text","label":"Origin/Country"},{"name":"organic","type":"boolean","label":"Organic"},{"name":"packaging","type":"text","label":"Packaging Size (kg)"}]'),
('fertilizers-chemicals', 'Fertilizers & Chemicals', 'fertilizers-chemicals', 'Fertilizers and agricultural chemicals', '🧪', 'agriculture', 115, 1, '[{"name":"productType","type":"select","label":"Product Type","options":["Fertilizer","Pesticide","Herbicide","Fungicide","Soil Amendment","Other"]},{"name":"organic","type":"boolean","label":"Organic"},{"name":"applicationMethod","type":"text","label":"Application Method"},{"name":"coverageArea","type":"text","label":"Coverage Area"}]'),
('fish-aquaculture', 'Fish & Aquaculture', 'fish-aquaculture', 'Fish and aquaculture products', '🐟', 'agriculture', 116, 1, '[{"name":"fishSpecies","type":"text","label":"Fish Species"},{"name":"weight","type":"number","label":"Average Weight (kg)"},{"name":"age","type":"text","label":"Age/Maturity"},{"name":"waterType","type":"select","label":"Water Type","options":["Freshwater","Saltwater","Brackish"]}]'),
('other-agricultural', 'Other Agricultural', 'other-agricultural', 'Other agricultural products', '🌾', 'agriculture', 117, 1, '[]');

-- Verification
SELECT 'Total categories inserted: ' || COUNT(*) FROM listing_categories;
